Updated guide to use the new tailscale funnel commands
BlueBubblesApp/bluebubbles-docs pull request #6
Opened 2023-04-09 02:31 UTC by arjanflac

Updated guide to use the new tailscale funnel commands & added info to use on host system when using a virtutal macOS

2023-04-09 04:20 UTC, jjoelj requested changes
Great! Minor changes requested.

2023-04-09 04:20 UTC, jjoelj commented on server/advanced/byo-proxy-service-guides/tailscale-vpn-setup.md
> -description: >-
I think you should keep some sort of description directly under the first header to keep the format the same as the other guides. It gives some context about what prerequisites there are to use this guide (e.g. having a Tailscale account). The distinction of this being an option that doesn't involve port-forwarding is also important.

2023-04-09 04:20 UTC, jjoelj commented on server/advanced/byo-proxy-service-guides/tailscale-vpn-setup.md
> +## Run on Host System |  macOS virutal machine
Could you clarify what this header means and/or reword it.

2023-04-10 17:13 UTC, tneotia requested changes
LGTM otherwise

2023-04-10 17:13 UTC, tneotia commented on server/advanced/byo-proxy-service-guides/tailscale-vpn-setup.md
> +```
Can you clarify that this port # could be different depending on what the user has set up (but indicate that its usually 1234)

2023-04-10 17:13 UTC, tneotia commented on server/advanced/byo-proxy-service-guides/tailscale-vpn-setup.md
> +<https://machine-name.example.ts.net:443/>
I don't think the <> are needed here

2023-04-10 19:59 UTC, merged